### ISSUE TITLE
[suggestion] config file

### ISSUE THREAD

**Issue by earthyie** [GitPois1x/DragonLoot#10]
It would be really useful if you could make a config file where we could change the stats of the armour and the number of scales that drop from killing the ender dragon so people could balance the armour themselves, it would also stop a lot of people from complaining

**Comment by Globox1997** [comment]
Added with commit [https://github.com/GitPois1x/DragonLoot/commit/e18e2e898401165374db1dbdbd9475246bd45d8d](https://github.com/GitPois1x/DragonLoot/commit/e18e2e898401165374db1dbdbd9475246bd45d8d)
