### ISSUE TITLE
[SUGGESTION] Netherite Plus Mod (Netherite Elytra)

### ISSUE THREAD

**Issue by srnyx** [GitPois1x/DragonLoot#12]
Could you make it so you can combine Dragon Scale Chestplate and Netherite Elytra from [Netherite Plus Mod](https://www.curseforge.com/minecraft/mc-mods/netherite-plus-mod)?
_The Netherite Elytra doesn't burn in lava, has double durability, and gives 4 armor points._

**Comment by Globox1997** [comment]
Added dynamic recipes, if netherite plus mod is installed, the only way to craft the winged dragon chestplate is combine it with the netherite elytra
