### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by K0KE11** [GitPois1x/DragonLoot#13]
I wanna change the durability of everything because the enderite mod is better and this looks cooler so I would like to raise the durability of the items so it's more powerful than the enderite, where can i find that, I checked in items and stuff but didn't find it

**Comment by Globox1997** [comment]
Durability of items aren't editable but the goal of this mod is to be balanced with vanilla

**Comment by Globox1997** [comment]
added a config to chance durability :) [https://github.com/GitPois1x/DragonLoot/commit/9c7bd29aa6d8294978a0f49d510445a2967b0f56](https://github.com/GitPois1x/DragonLoot/commit/9c7bd29aa6d8294978a0f49d510445a2967b0f56)
