### ISSUE TITLE
[SUGGESTION] Add an advancement 

### ISSUE THREAD

**Issue by Jamychal1** [GitPois1x/DragonLoot#14]
This mod itself is really great, but to match the end theme there should be an advancement somewhat similar to cover me in debris that says "The Armor at The End of The Game

**Comment by Globox1997** [comment]
Pretty cool idea, added it with [https://github.com/GitPois1x/DragonLoot/commit/fda8b345b5194e5d459c74d70300f1f0ac0de734](https://github.com/GitPois1x/DragonLoot/commit/fda8b345b5194e5d459c74d70300f1f0ac0de734)
