### ISSUE TITLE
[ISSUE] Bows are stackable

### ISSUE THREAD

**Issue by Jamychal1** [GitPois1x/DragonLoot#15]
While testing out the newest version, I came across a bug that bows are actually stackable.

**Comment by Globox1997** [comment]
Thanks for reporting it, fixed with [https://github.com/GitPois1x/DragonLoot/commit/9c7bd29aa6d8294978a0f49d510445a2967b0f56](https://github.com/GitPois1x/DragonLoot/commit/9c7bd29aa6d8294978a0f49d510445a2967b0f56)
