### ISSUE TITLE
Incompatible with Elytra Hopping

### ISSUE THREAD

**Issue by srnyx** [GitPois1x/DragonLoot#16]
https://paste.srnyx.xyz/cojogezotu.kotlin

**Comment by Globox1997** [comment]
Should be also fixed with [https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb](https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb)

**Comment by Globox1997** [comment]
reopen when this bug still occurs with the comming update
