### ISSUE TITLE
Startup server warning

### ISSUE THREAD

**Issue by srnyx** [GitPois1x/DragonLoot#17]
https://paste.srnyx.xyz/ohuwugexez.properties

**Comment by Globox1997** [comment]
fixed with [https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb](https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb)
