### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by TheAyres** [GitPois1x/DragonLoot#22]
Hello, I wanna to change the damage of the Dragon Scale items, because it have a incredible texture and is so much hard to get than the swords of other Mods, I don't know how or where I need to go for editing this, I look for the json file and I only find the durability and armor defense editing text

**Comment by Globox1997** [comment]
Added a config [https://github.com/GitPois1x/DragonLoot/commit/d91ab0c0e23d894bfcbc2de3aeb2dbd55a2890cd](https://github.com/GitPois1x/DragonLoot/commit/d91ab0c0e23d894bfcbc2de3aeb2dbd55a2890cd)
