### ISSUE TITLE
Dragon Loot 1.17 Latest Version

### ISSUE THREAD

**Issue by SHXRKIEgg** [GitPois1x/DragonLoot#26]
Not sure if other mods could be affecting it but in my [Better Minecraft FABRIC](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric) pack when you first get any item like wood or dirt you instantly get the achievement of dragon loot, some other developer mentioned that they changed the advancements in 1.17.

**Comment by Globox1997** [comment]
Yes in 1.17 advancements got changed but it is already fixed in dragon loot, just not uploaded

**Comment by SHXRKIEgg** [comment]
when will you upload the new version with the fix?

**Comment by Globox1997** [comment]
Not sure when I updated it but it is definitely fixed
