### ISSUE TITLE
Custom datapack recipies for CompatRecipes.java

### ISSUE THREAD

**Issue by Lukebb04** [GitPois1x/DragonLoot#29]
allow datapacks to overwrite CompatRecipes.java recipes

**Comment by Globox1997** [comment]
You can overwrite recipes with a datapack. The file names just have to be correct.
Check out the first strings of each recipe addition, that should be it here: [https://github.com/GitPois1x/DragonLoot/blob/1.18/src/main/java/net/dragonloot/compat/recipes/CompatRecipes.java](https://github.com/GitPois1x/DragonLoot/blob/1.18/src/main/java/net/dragonloot/compat/recipes/CompatRecipes.java)
Example is `dragon_bow.json`
