### ISSUE TITLE
Remove damage thing from dragon horse armor

### ISSUE THREAD

**Issue by alexmozaidze** [GitPois1x/DragonLoot#30]
The dragon horse armor has a damage thing, which vanilla horse armor doesn't. It kinda bothers me since I use TillItBreaks mod, that shows durability of things that have the said durability and it's annoying to see durability on thing that isn't supposed to break

**Comment by Globox1997** [comment]
Removed with [https://github.com/GitPois1x/DragonLoot/commit/2887f93484ef11b7b215ff561c7968f54103bc53](https://github.com/GitPois1x/DragonLoot/commit/2887f93484ef11b7b215ff561c7968f54103bc53)
