### ISSUE TITLE
Add TillItBreaks compatibility

### ISSUE THREAD

**Issue by alexmozaidze** [GitPois1x/DragonLoot#31]
TillItBreaks shows the amount of arrows you have on the bow, but it doesn't for dragon bow and crossbow

**Comment by Globox1997** [comment]
TillItBreaks dev can add compatibility by themselves here for example: [https://github.com/Schauweg/TillitBreaks/blob/master/src/main/java/schauweg/tillitbreaks/mixin/ItemRendererMixin.java#L60](https://github.com/Schauweg/TillitBreaks/blob/master/src/main/java/schauweg/tillitbreaks/mixin/ItemRendererMixin.java#L60)
