### ISSUE TITLE
When I try to open the game it says "The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dragonloot'! Exit Code: -1"

### ISSUE THREAD

**Issue by DrakeIsCool21** [GitPois1x/DragonLoot#34]
![Minecraft Launcher 11_23_2021 10_47_35 AM](https://user-images.githubusercontent.com/94919533/143056774-febcc5e3-ced3-4186-b987-d32ad01aa75f.png)

**Comment by Globox1997** [comment]
Please paste the crash log here :)

**Comment by R-unic** [comment]
same thing for me. only other mods i was using were REI and optifine+optifabric. i tried removing both, same result

**Comment by Globox1997** [comment]
Which mod version do you use and please paste the crash log here :)

**Comment by Globox1997** [comment]
dragon loot requires cloth config [https://www.curseforge.com/minecraft/mc-mods/cloth-config](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
