### ISSUE TITLE
The bow, crossbow, and trident in dragon scale cannot have their unlock levels changed with levelz

### ISSUE THREAD

**Issue by Whit3mar3** [GitPois1x/DragonLoot#35]
I'm trying to modify the level at which we unlock the dragon loot items thanks to the levelz mod via datapacks,

But I can't differentiate the bow, the crossbow and the trident from their dragon scale forms.
Can you create a way to do it through materials as well as tools ?

**Comment by Globox1997** [comment]
This is an issue for the levelz repository :)

**Comment by Globox1997** [comment]
You can edit them via datapacks. I recommend to use the material which is "dragon"
