### ISSUE TITLE
Dragon helmet doesn't cover the back of a player skin's hat (the 2nd layer)

### ISSUE THREAD

**Issue by Dejeh** [GitPois1x/DragonLoot#38]

**Comment by Globox1997** [comment]
Can you provide a screenshot?

**Comment by Dejeh** [comment]
![ok](https://user-images.githubusercontent.com/72144320/149869951-da2f1e91-3807-46ae-9320-4dd75c137a44.png)
![ok2](https://user-images.githubusercontent.com/72144320/149869969-45e11e9f-2961-4c4d-8d1f-18bfa3cef460.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/GitPois1x/DragonLoot/commit/f9177c8fcc73627c038ea20437982f110439f326](https://github.com/GitPois1x/DragonLoot/commit/f9177c8fcc73627c038ea20437982f110439f326)
Thanks for reporting
