### ISSUE TITLE
Odd explosion mechanics

### ISSUE THREAD

**Issue by Dejeh** [GitPois1x/DragonLoot#39]
dragonloot v1.0.10

most of the dropped items don't explode by creepers/TNT except for:

1. dragon anvil
2. dragon horse armor
3. dragon trident

is this intended? they ALWAYS explode.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/GitPois1x/DragonLoot/commit/0310287083db0fb3884ea2470994c95b58591441](https://github.com/GitPois1x/DragonLoot/commit/0310287083db0fb3884ea2470994c95b58591441)
