### ISSUE TITLE
It crashes my game

### ISSUE THREAD

**Issue by Kymor5** [GitPois1x/DragonLoot#4]
I am using fabric 1.16.4, and when I try to load version 1.0.3 of this mod, my game crashes. It says error code 0, meaning it was an unknown crash. This only happens whenever I load this mod. I have no idea why, and I was not provided with a crash report.

**Comment by Globox1997** [comment]
any other mods you have installed?

**Comment by Kymor5** [comment]
I have many more mods installed, around 90. However the game only crashes when I add DragonLoot to my mods folder.

**Comment by Globox1997** [comment]
yes because another mod is incompatible with dragonloot :D
No expensive mod for example

**Comment by Kymor5** [comment]
ah ok
