### ISSUE TITLE
[Suggestion] Anvil Config

### ISSUE THREAD

**Issue by tarkidu** [GitPois1x/DragonLoot#42]
Can you add a config for the Dragon anvil? Love the idea to override the limit but would like to disable the 30 levels cap.

**Comment by Globox1997** [comment]
Added with [https://github.com/GitPois1x/DragonLoot/commit/9e6a5abe163ac23ee6755d01630b3506a748318e](https://github.com/GitPois1x/DragonLoot/commit/9e6a5abe163ac23ee6755d01630b3506a748318e)
