### ISSUE TITLE
Anvil Crash

### ISSUE THREAD

**Issue by LAWERD** [GitPois1x/DragonLoot#45]
Whenever I Click an anvil, doesnt matter what anvil it is, my game crashes. i have confirmed its not just my pc by inviting my friends and it crashed for them too for some reason. i downloaded the latest version (1.18.2) and maybe its unstable idk anyways heres the crash log:

https://paste.gg/p/anonymous/7b51c23221c94b5fabaf1ee1b386bbdb

**Comment by SplendidAlakey** [comment]
This crash seems to have nothing to do with DragonLoot, see lines 41, 42. Report to BCLib, see what they say.

**Comment by Globox1997** [comment]
Thanks for looking into it Footage2 :) looks like bclib does some bad things, crash is not on this mods side
