### ISSUE TITLE
Unable to find and change/delete the dragon helemts model

### ISSUE THREAD

**Issue by lxly9** [GitPois1x/DragonLoot#46]
I need to change it because of visual glitches with the 2nd skin layer (and would love to reduce it to the minimal armor from a texture pack)

**Comment by Globox1997** [comment]
Fixed the 2nd skin layer issue with [https://github.com/GitPois1x/DragonLoot/commit/f9177c8fcc73627c038ea20437982f110439f326](https://github.com/GitPois1x/DragonLoot/commit/f9177c8fcc73627c038ea20437982f110439f326)
The model can't get edited cause it is a entity model
