### ISSUE TITLE
Amethyst treats Dragon tools as nonplayer mined

### ISSUE THREAD

**Issue by SplendidAlakey** [GitPois1x/DragonLoot#47]
**MC** 1.18.2
**Fabric API** 0.51.1
**Cloth Config** 6.2.62
**DragonLoot** 1.0.10

To reproduce:

1. Get a Dragon Pickaxe and a bunch of amethyst clusters
2. Enchant your pickaxe with Fortune 3; place the clusters down anywhere you want
3. Break the clusters with your enchanted pickaxe

Expected result: amethyst shards drop in quantities of 4-16, calculated depending on the level of Fortune.

Actual result: amethyst shards drop in quantities of exactly 2, which should not be possible at all when the cluster is broken directly by a player.

Logs: https://gist.github.com/Footage2-Amply-Pounce/1d5cb548163e9f0321da1c6a16131b05

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/GitPois1x/DragonLoot/commit/3d5a19b9f54aa243315668c207bb78f44e8883e2](https://github.com/GitPois1x/DragonLoot/commit/3d5a19b9f54aa243315668c207bb78f44e8883e2)
