### ISSUE TITLE
[feature request] Netherite Plus -> Dragon Scale

### ISSUE THREAD

**Issue by milkev** [GitPois1x/DragonLoot#5]
Is it planned to add Dragon Scale levels of gear for [Netherite Plus](https://www.curseforge.com/minecraft/mc-mods/netherite-plus-mod)?

Things like a "Dragon Scale Fishing Rod" and "Dragon Scale Trident".

I think it would be a great addition to your mod.

**Comment by Globox1997** [comment]
Added some compatibility items with [https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb](https://github.com/GitPois1x/DragonLoot/commit/de9e841a620e972017a6a9fb6aea63f1bdf12feb)
