### ISSUE TITLE
Ability to edit armor toughness, durability, mining speed, and damage BY SPECIFIED NUMBER

### ISSUE THREAD

**Issue by TheSkeletonAppears** [GitPois1x/DragonLoot#54]
I feel like the dragon armor is underpowered in a way so I hope this gets added to the config

**Comment by Globox1997** [comment]
Added new config settings with [https://github.com/GitPois1x/DragonLoot/commit/d43ec8e6fc31a1982bcd8ec8d722a71110661f25](https://github.com/GitPois1x/DragonLoot/commit/d43ec8e6fc31a1982bcd8ec8d722a71110661f25)
