### ISSUE TITLE
Other Mod Incompatibilities

### ISSUE THREAD

**Issue by dlbliverpool** [GitPois1x/DragonLoot#55]
Is there a way of fixing this issue, basically, my dragon pickaxe doesnt work on any ores added by any other mod which i thought wouldnt be an issue, like i thought there would just be a certain power needed to break each one, but it doesnt work like that i suppose, I'd also assume the same goes for the axe and shovel, i assume it will have normal fist breaking speed for anything added by another mod

**Comment by Globox1997** [comment]
Might be fixed with [https://github.com/GitPois1x/DragonLoot/commit/42a9259f43355b5ead73916518f3b484c3476bd1](https://github.com/GitPois1x/DragonLoot/commit/42a9259f43355b5ead73916518f3b484c3476bd1)
I guess you are talking about mc 1.19 version?
