### ISSUE TITLE
Recipes missing from game despite items working

### ISSUE THREAD

**Issue by AmbivalentX** [GitPois1x/DragonLoot#57]
I am able to grab the items this mod adds from the creative menu, and the dragon drops scales, but I cannot use any of the recipes to create the items. They are missing from the recipe book and if I place the items in a crafting bench myself, no result is shown. This also applies to the Dragon Anvil, I cannot upgrade armour with it. I have tried using "/recipe give" to give myself the recipes but it said "No new recipes were learned". I also tried removing and adding the recipes from myself and that didn't work either.

**Comment by Globox1997** [comment]
Do you play with a modpack? try to test only with this mod installed (and its dependencies)

**Comment by Globox1997** [comment]
Added recipes to the recipe book with [https://github.com/GitPois1x/DragonLoot/commit/9aaa03a0c90fd911216e4042210ef4fdc6bfdcf7](https://github.com/GitPois1x/DragonLoot/commit/9aaa03a0c90fd911216e4042210ef4fdc6bfdcf7)

**Comment by Globox1997** [comment]
Reopen with further information
