### ISSUE TITLE
Is the mod expected to work on 1.19.4?

### ISSUE THREAD

**Issue by mrcrashmer** [GitPois1x/DragonLoot#66]
meow

**Comment by Nitjsefnie** [comment]
Just made https://github.com/GitPois1x/DragonLoot/pull/67, waiting for approval and merge

**Comment by mrcrashmer** [comment]
The issue is closed, the update has been performed by other mods creator (if you need to update, look here  #67) The mod is awaiting acceptance for an update from the author :)
Special thanks to @Nitjsefnie, for the update and help. As many as six servers were able to upgrade to the latest version of the game :smile:
