### ISSUE TITLE
This Mod is very Unbalanced

### ISSUE THREAD

**Issue by The-VoidX3** [GitPois1x/DragonLoot#8]
1. This mod makes the elytra completely useless
    - you should have to combine an elytra with the dragon scale chestplate or craft a dragon scale elytra then combine it with a 
       dragon scale chestplate
    - also the fact that using the elytra doesn't use any durability is kind of op 

2. the fact that you kill the dragon once and you have all the scales you will ever need is broken
    - you should have to craft the scales into another item which you use to upgrade the armor (like how netherite works)

**Comment by GitPois1x** [comment]
Both of these have already been changed I just haven't updated yet. 
Double checking a few things and updating some time today.

**Comment by Globox1997** [comment]
split the chestplate into two [https://github.com/GitPois1x/DragonLoot/commit/bf3a32bf300741cca2b32f67d6ccde557fe05680](https://github.com/GitPois1x/DragonLoot/commit/bf3a32bf300741cca2b32f67d6ccde557fe05680)
