### ISSUE TITLE
1.21 Items durability and enchanting table bug

### ISSUE THREAD

**Issue by mo0nylighty** [GitPois1x/DragonLoot#85]
1.21 DragonLoot items like pickaxe, sword, bow, etc. have 37 durability except armor
also none of items in this version are enchantable through enchanting table and /enchant command

**Comment by cutekita** [comment]
for me the pickaxe also seems to be on wood level, so breaking iron ore or above doesnt drop anything

**Comment by Dekooh-Rm** [comment]
the mod as a whole has many problems, for me even the trident just being thrown crashes the game

**Comment by Globox1997** [comment]
Fixed the problems with [https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb](https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb)
