### ISSUE TITLE
Completely bugged out as of 1.1.4 (fabric 1.16, minecraft 1.21)

### ISSUE THREAD

**Issue by Dekooh-Rm** [GitPois1x/DragonLoot#86]
None of the items in this version are enchantable through the enchantment table and /enchant command. Pickaxe is on wood level and trident crashes the game when touching an entity.

**Comment by Globox1997** [comment]
Fixed those bugs with [https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb](https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb)
