### ISSUE TITLE
Dragon trident crashing game 1.21

### ISSUE THREAD

**Issue by oBlue22** [GitPois1x/DragonLoot#87]
i made a dragon trident with loyalty 3 the first time i threw it when it came back my game crashed, every time i rejoin the server the trident will randomly fly at me and crash my game it has effectively hard locked my server any help would be amazing!! did not happen before it was upgraded to dragon

**Comment by Globox1997** [comment]
Your trident will loose all enchantments with this fix but in the future it will work: [https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb](https://github.com/GitPois1x/DragonLoot/commit/4cf62cd1880ac04b108b2b739d25f5a2714cf8fb)
