### ISSUE TITLE
Certain items unenchantable and trident crashes the game

### ISSUE THREAD

**Issue by Dekooh-Rm** [GitPois1x/DragonLoot#88]
As of dragon loot 1.1.5, fabric 1.16 and minecraft 1.21, any time a trident from this mod is thrown at an entity it crashes the game, and the items shown below cannot be enchanted properly in survival or with the /enchant command.
![image_2024-07-20_171535758](https://github.com/user-attachments/assets/83b53f11-ee86-4c17-8030-fe5788afae06)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/GitPois1x/DragonLoot/commit/5b7b7a25d36d7730d172a172e6e594392cb0e876](https://github.com/GitPois1x/DragonLoot/commit/5b7b7a25d36d7730d172a172e6e594392cb0e876)
