### ISSUE TITLE
Trident Problem

### ISSUE THREAD

**Issue by Dekooh-Rm** [GitPois1x/DragonLoot#90]
So i've recently added multiple issue posts that were "solved" in recent updates regarding the trident and some other stuff in the mod, but it turns out only the trident has been keeping these issues even after those updates so i'd assume it's a problem regarding my modpack.
The issue being that it crashes the game and corrupts any world when i try to throw a trident from this mod at an entity.
The mod version i'm using right now is 1.1.6 with Fabric 1.16 and Minecraft 1.21.
If there is any more info needed to possibly fix this compatability issue, i'd happily supply it.

**Comment by Globox1997** [comment]
Pls provide latest log

**Comment by Dekooh-Rm** [comment]
[latest.log](https://github.com/user-attachments/files/16412922/latest.log)
There you go, hope it helps.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/GitPois1x/DragonLoot/commit/b552e309a307618128c4032c8f8b2696f4cef41a](https://github.com/GitPois1x/DragonLoot/commit/b552e309a307618128c4032c8f8b2696f4cef41a)
